globals:
  debug: False
  seed: 1213
  device: cuda
  num_epochs: 45
  folds:
    - 0

data:
  train_df_path: data_ignore/external_dataset/32khz/birdsong-resampled-train-audio-01/train_mod.csv
  train_audio_path: data_ignore/external_dataset/32khz
  test_df_path: ./data/external_dataset/birdcall-check/test_audio
  test_audio_path: ./data/external_dataset/birdcall-check/test.csv

split:
  name: StratifiedKFold
  params:
    n_splits: 5
    random_state: 42
    shuffle: True

dataset:
  name: SpectrogramDataset
  img_size: 224
  params:
    n_mels: 128
    fmin: 20
    fmax: 16000

loader:
  train:
    batch_size: 20
    shuffle: True
    num_workers: 2
  valid:
    batch_size: 10
    shuffle: False
    num_workers: 2

model:
  name: ResNet50
  params:
    base_model: resnet50
    pretrained: True
    n_classes: 264

loss:
  name: ResNetLoss
  params:
    loss_type: bce

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10

hydra:
  run:
    dir: ./data/hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}/try0
  sweep:
    dir: ./data/hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: try${hydra.job.num}
  job_logging:
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s] line%(lineno)d [%(levelname)s] %(message)s'
